; Generated by tools/gen_art_portrait.py: do not edit. The art turned for the portrait screen.
        .include "art.inc"
        .export sprite_lo, sprite_hi, sprite_dx, sprite_dy

        .segment "RODATA"
spr_player:   ; 8x8 turned
    .byte 6, $01, $20, $00, $00, $00
    .byte 6, $03, $32, $00, $00, $00
    .byte 6, $03, $33, $31, $00, $00
    .byte 6, $23, $31, $11, $11, $00
    .byte 6, $23, $31, $11, $11, $00
    .byte 6, $03, $33, $31, $00, $00
    .byte 6, $03, $32, $00, $00, $00
    .byte 6, $01, $20, $00, $00, $00
    .byte 0
spr_player_red:   ; 8x8 turned
    .byte 6, $0f, $50, $00, $00, $00
    .byte 6, $02, $25, $00, $00, $00
    .byte 6, $02, $22, $2f, $00, $00
    .byte 6, $52, $2f, $ff, $ff, $00
    .byte 6, $52, $2f, $ff, $ff, $00
    .byte 6, $02, $22, $2f, $00, $00
    .byte 6, $02, $25, $00, $00, $00
    .byte 6, $0f, $50, $00, $00, $00
    .byte 0
spr_pbul:   ; 6x2 turned
    .byte 5, $bb, $bb, $bb, $00
    .byte 5, $bb, $bb, $bb, $00
    .byte 0
spr_ebul:   ; 4x2 turned
    .byte 4, $82, $28, $00
    .byte 4, $82, $28, $00
    .byte 0
spr_bee_a:   ; 6x8 turned
    .byte 5, $00, $03, $33, $00
    .byte 5, $00, $33, $30, $00
    .byte 5, $03, $33, $35, $00
    .byte 5, $35, $53, $33, $00
    .byte 5, $35, $53, $33, $00
    .byte 5, $03, $33, $35, $00
    .byte 5, $00, $33, $30, $00
    .byte 5, $00, $03, $33, $00
    .byte 0
spr_bee_b:   ; 6x8 turned
    .byte 5, $03, $30, $00, $00
    .byte 5, $33, $33, $00, $00
    .byte 5, $03, $33, $35, $00
    .byte 5, $35, $53, $33, $00
    .byte 5, $35, $53, $33, $00
    .byte 5, $03, $33, $35, $00
    .byte 5, $33, $33, $00, $00
    .byte 5, $03, $30, $00, $00
    .byte 0
spr_bfly_a:   ; 6x8 turned
    .byte 5, $00, $02, $f2, $00
    .byte 5, $02, $22, $20, $00
    .byte 5, $22, $22, $45, $00
    .byte 5, $22, $24, $14, $00
    .byte 5, $22, $24, $14, $00
    .byte 5, $22, $22, $45, $00
    .byte 5, $02, $22, $20, $00
    .byte 5, $00, $02, $f2, $00
    .byte 0
spr_bfly_b:   ; 6x6 turned
    .byte 5, $02, $02, $f0, $00
    .byte 5, $22, $22, $45, $00
    .byte 5, $22, $24, $14, $00
    .byte 5, $22, $24, $14, $00
    .byte 5, $22, $22, $45, $00
    .byte 5, $02, $02, $f0, $00
    .byte 0
spr_boss_a:   ; 7x8 turned
    .byte 5, $60, $66, $00, $00
    .byte 5, $66, $68, $65, $00
    .byte 5, $06, $65, $65, $00
    .byte 5, $66, $66, $64, $40
    .byte 5, $66, $66, $64, $40
    .byte 5, $06, $65, $65, $00
    .byte 5, $66, $68, $65, $00
    .byte 5, $60, $66, $00, $00
    .byte 0
spr_boss_b:   ; 7x8 turned
    .byte 5, $00, $66, $00, $00
    .byte 5, $66, $68, $65, $00
    .byte 5, $66, $65, $65, $00
    .byte 5, $66, $66, $64, $40
    .byte 5, $66, $66, $64, $40
    .byte 5, $66, $65, $65, $00
    .byte 5, $66, $68, $65, $00
    .byte 5, $00, $66, $00, $00
    .byte 0
spr_bossp_a:   ; 7x8 turned
    .byte 5, $70, $77, $00, $00
    .byte 5, $77, $78, $75, $00
    .byte 5, $07, $75, $75, $00
    .byte 5, $77, $77, $74, $40
    .byte 5, $77, $77, $74, $40
    .byte 5, $07, $75, $75, $00
    .byte 5, $77, $78, $75, $00
    .byte 5, $70, $77, $00, $00
    .byte 0
spr_bossp_b:   ; 7x8 turned
    .byte 5, $00, $77, $00, $00
    .byte 5, $77, $78, $75, $00
    .byte 5, $77, $75, $75, $00
    .byte 5, $77, $77, $74, $40
    .byte 5, $77, $77, $74, $40
    .byte 5, $77, $75, $75, $00
    .byte 5, $77, $78, $75, $00
    .byte 5, $00, $77, $00, $00
    .byte 0
spr_expl1:   ; 4x4 turned
    .byte 4, $05, $50, $00
    .byte 4, $51, $15, $00
    .byte 4, $51, $15, $00
    .byte 4, $05, $50, $00
    .byte 0
spr_expl2:   ; 8x8 turned
    .byte 6, $00, $08, $80, $00, $00
    .byte 6, $52, $85, $58, $25, $00
    .byte 6, $08, $51, $15, $80, $00
    .byte 6, $05, $11, $11, $50, $00
    .byte 6, $05, $11, $11, $50, $00
    .byte 6, $08, $51, $15, $80, $00
    .byte 6, $52, $85, $58, $25, $00
    .byte 6, $00, $08, $80, $00, $00
    .byte 0
spr_expl3:   ; 8x8 turned
    .byte 6, $50, $85, $58, $05, $00
    .byte 6, $05, $02, $20, $50, $00
    .byte 6, $00, $50, $05, $00, $00
    .byte 6, $20, $05, $50, $02, $00
    .byte 6, $20, $05, $50, $02, $00
    .byte 6, $00, $50, $05, $00, $00
    .byte 6, $05, $02, $20, $50, $00
    .byte 6, $50, $85, $58, $05, $00
    .byte 0
spr_pexp1:   ; 4x4 turned
    .byte 4, $01, $10, $00
    .byte 4, $11, $11, $00
    .byte 4, $11, $11, $00
    .byte 4, $01, $10, $00
    .byte 0
spr_pexp2:   ; 8x8 turned
    .byte 6, $00, $05, $50, $00, $00
    .byte 6, $00, $11, $11, $00, $00
    .byte 6, $05, $45, $54, $50, $00
    .byte 6, $51, $11, $11, $15, $00
    .byte 6, $51, $11, $11, $15, $00
    .byte 6, $05, $45, $54, $50, $00
    .byte 6, $00, $11, $11, $00, $00
    .byte 6, $00, $05, $50, $00, $00
    .byte 0
spr_pexp3:   ; 8x8 turned
    .byte 6, $00, $18, $81, $00, $00
    .byte 6, $51, $48, $84, $15, $00
    .byte 6, $01, $18, $81, $10, $00
    .byte 6, $04, $81, $18, $40, $00
    .byte 6, $04, $81, $18, $40, $00
    .byte 6, $01, $18, $81, $10, $00
    .byte 6, $51, $48, $84, $15, $00
    .byte 6, $00, $18, $81, $00, $00
    .byte 0
spr_pexp4:   ; 8x8 turned
    .byte 6, $15, $18, $04, $55, $00
    .byte 6, $40, $50, $10, $01, $00
    .byte 6, $01, $00, $08, $40, $00
    .byte 6, $58, $41, $51, $81, $00
    .byte 6, $58, $41, $51, $81, $00
    .byte 6, $01, $00, $08, $40, $00
    .byte 6, $40, $50, $10, $01, $00
    .byte 6, $15, $18, $04, $55, $00
    .byte 0
spr_beam_0_0:   ; 4x12 turned
    .byte 4, $03, $03, $00
    .byte 4, $30, $30, $00
    .byte 4, $03, $03, $00
    .byte 4, $30, $30, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $04, $04, $00
    .byte 4, $40, $40, $00
    .byte 4, $04, $04, $00
    .byte 4, $40, $40, $00
    .byte 0
spr_beam_0_1:   ; 4x12 turned
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $04, $04, $00
    .byte 4, $40, $40, $00
    .byte 4, $04, $04, $00
    .byte 4, $40, $40, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 0
spr_beam_0_2:   ; 4x12 turned
    .byte 4, $04, $04, $00
    .byte 4, $40, $40, $00
    .byte 4, $04, $04, $00
    .byte 4, $40, $40, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $03, $03, $00
    .byte 4, $30, $30, $00
    .byte 4, $03, $03, $00
    .byte 4, $30, $30, $00
    .byte 0
spr_beam_0_3:   ; 4x12 turned
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $03, $03, $00
    .byte 4, $30, $30, $00
    .byte 4, $03, $03, $00
    .byte 4, $30, $30, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 0
spr_beam_1_0:   ; 4x12 turned
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $04, $04, $00
    .byte 4, $40, $40, $00
    .byte 4, $04, $04, $00
    .byte 4, $40, $40, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 0
spr_beam_1_1:   ; 4x12 turned
    .byte 4, $04, $04, $00
    .byte 4, $40, $40, $00
    .byte 4, $04, $04, $00
    .byte 4, $40, $40, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $03, $03, $00
    .byte 4, $30, $30, $00
    .byte 4, $03, $03, $00
    .byte 4, $30, $30, $00
    .byte 0
spr_beam_1_2:   ; 4x12 turned
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $03, $03, $00
    .byte 4, $30, $30, $00
    .byte 4, $03, $03, $00
    .byte 4, $30, $30, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 0
spr_beam_1_3:   ; 4x12 turned
    .byte 4, $03, $03, $00
    .byte 4, $30, $30, $00
    .byte 4, $03, $03, $00
    .byte 4, $30, $30, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $04, $04, $00
    .byte 4, $40, $40, $00
    .byte 4, $04, $04, $00
    .byte 4, $40, $40, $00
    .byte 0
spr_beam_2_0:   ; 4x20 turned
    .byte 4, $04, $04, $00
    .byte 4, $40, $40, $00
    .byte 4, $04, $04, $00
    .byte 4, $40, $40, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $03, $03, $00
    .byte 4, $30, $30, $00
    .byte 4, $03, $03, $00
    .byte 4, $30, $30, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $04, $04, $00
    .byte 4, $40, $40, $00
    .byte 4, $04, $04, $00
    .byte 4, $40, $40, $00
    .byte 0
spr_beam_2_1:   ; 4x20 turned
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $03, $03, $00
    .byte 4, $30, $30, $00
    .byte 4, $03, $03, $00
    .byte 4, $30, $30, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $04, $04, $00
    .byte 4, $40, $40, $00
    .byte 4, $04, $04, $00
    .byte 4, $40, $40, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 0
spr_beam_2_2:   ; 4x20 turned
    .byte 4, $03, $03, $00
    .byte 4, $30, $30, $00
    .byte 4, $03, $03, $00
    .byte 4, $30, $30, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $04, $04, $00
    .byte 4, $40, $40, $00
    .byte 4, $04, $04, $00
    .byte 4, $40, $40, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $03, $03, $00
    .byte 4, $30, $30, $00
    .byte 4, $03, $03, $00
    .byte 4, $30, $30, $00
    .byte 0
spr_beam_2_3:   ; 4x20 turned
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $04, $04, $00
    .byte 4, $40, $40, $00
    .byte 4, $04, $04, $00
    .byte 4, $40, $40, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $03, $03, $00
    .byte 4, $30, $30, $00
    .byte 4, $03, $03, $00
    .byte 4, $30, $30, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 0
spr_beam_3_0:   ; 4x28 turned
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $03, $03, $00
    .byte 4, $30, $30, $00
    .byte 4, $03, $03, $00
    .byte 4, $30, $30, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $04, $04, $00
    .byte 4, $40, $40, $00
    .byte 4, $04, $04, $00
    .byte 4, $40, $40, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $03, $03, $00
    .byte 4, $30, $30, $00
    .byte 4, $03, $03, $00
    .byte 4, $30, $30, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 0
spr_beam_3_1:   ; 4x28 turned
    .byte 4, $03, $03, $00
    .byte 4, $30, $30, $00
    .byte 4, $03, $03, $00
    .byte 4, $30, $30, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $04, $04, $00
    .byte 4, $40, $40, $00
    .byte 4, $04, $04, $00
    .byte 4, $40, $40, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $03, $03, $00
    .byte 4, $30, $30, $00
    .byte 4, $03, $03, $00
    .byte 4, $30, $30, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $04, $04, $00
    .byte 4, $40, $40, $00
    .byte 4, $04, $04, $00
    .byte 4, $40, $40, $00
    .byte 0
spr_beam_3_2:   ; 4x28 turned
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $04, $04, $00
    .byte 4, $40, $40, $00
    .byte 4, $04, $04, $00
    .byte 4, $40, $40, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $03, $03, $00
    .byte 4, $30, $30, $00
    .byte 4, $03, $03, $00
    .byte 4, $30, $30, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $04, $04, $00
    .byte 4, $40, $40, $00
    .byte 4, $04, $04, $00
    .byte 4, $40, $40, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 0
spr_beam_3_3:   ; 4x28 turned
    .byte 4, $04, $04, $00
    .byte 4, $40, $40, $00
    .byte 4, $04, $04, $00
    .byte 4, $40, $40, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $03, $03, $00
    .byte 4, $30, $30, $00
    .byte 4, $03, $03, $00
    .byte 4, $30, $30, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $04, $04, $00
    .byte 4, $40, $40, $00
    .byte 4, $04, $04, $00
    .byte 4, $40, $40, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $0b, $0b, $00
    .byte 4, $b0, $b0, $00
    .byte 4, $03, $03, $00
    .byte 4, $30, $30, $00
    .byte 4, $03, $03, $00
    .byte 4, $30, $30, $00
    .byte 0
sprite_lo: .byte <spr_player, <spr_player_red, <spr_pbul, <spr_ebul, <spr_bee_a, <spr_bee_b, <spr_bfly_a, <spr_bfly_b, <spr_boss_a, <spr_boss_b, <spr_bossp_a, <spr_bossp_b, <spr_expl1, <spr_expl2, <spr_expl3, <spr_pexp1, <spr_pexp2, <spr_pexp3, <spr_pexp4, <spr_beam_0_0, <spr_beam_0_1, <spr_beam_0_2, <spr_beam_0_3, <spr_beam_1_0, <spr_beam_1_1, <spr_beam_1_2, <spr_beam_1_3, <spr_beam_2_0, <spr_beam_2_1, <spr_beam_2_2, <spr_beam_2_3, <spr_beam_3_0, <spr_beam_3_1, <spr_beam_3_2, <spr_beam_3_3
sprite_hi: .byte >spr_player, >spr_player_red, >spr_pbul, >spr_ebul, >spr_bee_a, >spr_bee_b, >spr_bfly_a, >spr_bfly_b, >spr_boss_a, >spr_boss_b, >spr_bossp_a, >spr_bossp_b, >spr_expl1, >spr_expl2, >spr_expl3, >spr_pexp1, >spr_pexp2, >spr_pexp3, >spr_pexp4, >spr_beam_0_0, >spr_beam_0_1, >spr_beam_0_2, >spr_beam_0_3, >spr_beam_1_0, >spr_beam_1_1, >spr_beam_1_2, >spr_beam_1_3, >spr_beam_2_0, >spr_beam_2_1, >spr_beam_2_2, >spr_beam_2_3, >spr_beam_3_0, >spr_beam_3_1, >spr_beam_3_2, >spr_beam_3_3
sprite_dx: .byte 0, 0, 2, 4, 1, 1, 1, 1, 1, 1, 1, 1, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
sprite_dy: .byte 0, 0, 0, 3, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
