#!/usr/bin/env python3
"""Generate the art of the portrait ROM (-D PORTRAIT=1) into src/portrait/: font.s, art.s, art.inc.

The portrait field is drawn turned by 90 degrees on the 160 x 102 screen (Suzy cannot turn a sprite), so every picture is turned here, when
it is made. An upright picture (x to the right, y down) becomes a screen picture with
    screen X = h - 1 - y,  screen Y = x        (h = the height of the upright picture)
i.e. the top of the upright picture is at the right edge of the screen and its left edge at the top (the player turns the Lynx, or the emulator
turns the picture: the rotation byte of the header).

Sprites: the 16 x 16 pictures of ../psp/art.h (our own art) are cut down to 8 x 8 by a 2 x 2 filter (the most frequent colour of the four
pixels, at least two of them; an explosion keeps single pixels) and the 16 Lynx pens. The field has 0.88 units per arcade pixel and 2 units are
one Lynx pixel, so a sprite box is 8 x 8 pixels (16 units). The offsets sprite_dx / sprite_dy put the turned sprite where the turned box is:
the base point of a box at game (x, y) is the screen (122 - y / 2, x / 2) (view.s).

Font: the 3 x 5 glyphs turned (5 wide, 3 lines), 16 bytes each (the index * 16 stays).
Usage: python3 tools/gen_art_portrait.py [preview.png]
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, '..')
OUT = os.path.join(ROOT, 'src', 'portrait')
os.makedirs(OUT, exist_ok=True)
GLYPHS = {}
for m in re.finditer(r"'(.)': '([01]{15})'", open(os.path.join(HERE, 'gen_art.py')).read().split('def glyph')[0]):
    GLYPHS[m.group(1)] = m.group(2)

PENS = {'.': 0, 'w': 1, 'r': 2, 'b': 3, 'c': 4, 'y': 5, 'g': 6, 'p': 7, 'o': 8, 'x': 9, 'k': 10, 'l': 11, 'f': 15}   # pen letters (as gen_art.py)


def rotate(rows):
    """An upright picture (strings of equal length) turned for the screen: screen X = h - 1 - y, screen Y = x."""
    h, w = len(rows), len(rows[0])
    return [''.join(rows[h - 1 - x][y] for x in range(h)) for y in range(w)]


def encode(rows, label):
    """Suzy literal lines, 4 bpp, every line padded by one byte (the last pixel of a line is lost in Gearlynx)."""
    w = len(rows[0])
    out = []
    for r in rows:
        px = [PENS[ch] for ch in r.ljust(w + 2, '.')]
        px = px[:2 * (w // 2 + 1)]
        out.append('    .byte %d, ' % (len(px) // 2 + 1) + ', '.join('$%02x' % (px[i] << 4 | px[i + 1]) for i in range(0, len(px), 2)))
    out.append('    .byte 0')
    return out


# ------------------------------------------------------------------ font
lines = ['; Generated by tools/gen_art_portrait.py: do not edit. The 3 x 5 font turned: 5 wide, 3 lines.', '        .export font_w, font_r', '',
         '        .segment "RODATA"']
for name, pen in (('font_w', 'w'), ('font_r', 'r')):
    lines.append(f'{name}:')
    for c in range(32, 91):
        bits = GLYPHS.get(chr(c), '0' * 15)
        up = [''.join(pen if bits[r * 3 + k] == '1' else '.' for k in range(3)) for r in range(5)]   # 5 rows of 3
        rot = rotate(up)                                                                           # 3 lines of 5
        lines.append(f'    ; {chr(c)}')
        data = encode(rot, chr(c))
        lines += data
        size = sum(int(d.split()[1].rstrip(',')) for d in data[:-1]) + 1
        lines.append('    .res %d, 0' % (16 - size))
open(os.path.join(OUT, 'font.s'), 'w').write('\n'.join(lines) + '\n')

# ------------------------------------------------------------------ the art of psp/art.h
src = open(os.path.join(ROOT, '..', 'psp', 'art.h')).read()
ART = {}
for m in re.finditer(r'static ArtRows art_(\w+) = \{(.*?)\};', src, re.S):
    rows = re.findall(r'"([^"]*)"', m.group(2))
    ART[m.group(1)] = [r + r[::-1] for r in rows]                       # mirrored: 16 x 16

# variant: pens of the letters m (main), M (light), n (dark)
VARIANT = {'bee': ('b', 'l', 'b'), 'bfly': ('r', 'f', 'r'), 'boss': ('g', 'g', 'g'), 'bossp': ('p', 'p', 'p')}
COLOUR = {'y': 'y', 'Y': 'o', 'c': 'c', 'w': 'w', 'k': 'k', 'o': 'o', 'r': 'r', 'b': 'b', 'g': 'x'}
PRIORITY = 'wycor'


def to_pens(rows, variant):
    m = {'.': '.', 'm': variant[0], 'M': variant[1], 'n': variant[2]} if variant else {'.': '.'}
    return [''.join(m.get(ch, COLOUR.get(ch, '.')) for ch in r) for r in rows]


def cut(rows, sparse=False):
    """16 x 16 -> 8 x 8: the most frequent pen of each 2 x 2 block (a tie: the brighter special colours first, then by letter)."""
    out = []
    for y in range(0, 16, 2):
        line = ''
        for x in range(0, 8, 2):                                        # the left half: the art is mirrored, so is the cut
            blk = [rows[y][x], rows[y][x + 1], rows[y + 1][x], rows[y + 1][x + 1]]
            ink = [p for p in blk if p != '.']
            if len(ink) < (1 if sparse else 2):
                line += '.'
                continue
            best = max(sorted(set(ink)), key=lambda p: (ink.count(p), p in PRIORITY and 5 - PRIORITY.index(p)))
            line += best
        out.append(line + line[::-1])
    return out


def recolour(rows, table):
    return [''.join(table.get(ch, ch) for ch in r) for r in rows]


SPRITES = []                                                            # (name, upright rows, box x offset, box y offset): the rows are already cut to their box
SPRITES.append(('player', cut(to_pens(ART['player'], None))))
SPRITES.append(('player_red', recolour(cut(to_pens(ART['player'], None)), {'w': 'f', 'b': 'r', 'r': 'y', 'c': 'w'})))
SPRITES.append(('pbul', ['ll'] * 6))
SPRITES.append(('ebul', ['...oo...', '...rr...', '...rr...', '...oo...']))
for name, base in (('bee', 'bee'), ('bfly', 'bfly'), ('boss', 'boss'), ('bossp', 'boss')):
    for f in 'ab':
        SPRITES.append((f'{name}_{f}', cut(to_pens(ART[f'{base}_{f}'], VARIANT[name]))))
for n in (1, 2, 3):
    SPRITES.append((f'expl{n}', cut(to_pens(ART[f'xa{n - 1}'], None), True)))
for n in (1, 2, 3, 4):
    SPRITES.append((f'pexp{n}', cut(to_pens(ART[f'xp{n - 1}'], None), True)))

# The tractor beam: 4 rows, 4 x 4 pixel checkerboard cells in a shimmering colour, 4 colour phases. id = SP_BEAM + row * 4 + phase
BEAM_HW = (1, 1, 2, 3)                                                  # cells either side of the middle one
for r, hw in enumerate(BEAM_HW):
    for phase in range(4):
        rows = []
        for y in range(4):
            line = ''
            for k in range(2 * hw + 1):
                cc = 'blcl'[(k + r + phase) & 3]
                line += ''.join(cc if (x + y) % 2 == 0 else '.' for x in range(4))
            rows.append(line)
        SPRITES.append((f'beam_{r}_{phase}', rows))

BOX = 8                                                                 # the box of a game sprite (16 units)
asm = ['; Generated by tools/gen_art_portrait.py: do not edit. The art turned for the portrait screen.', '        .include "art.inc"',
       '        .export sprite_lo, sprite_hi, sprite_dx, sprite_dy', '', '        .segment "RODATA"']
inc = ['; Generated by tools/gen_art_portrait.py: do not edit. Sprite ids (index into sprite_lo/hi/dx/dy).']
dx_tab, dy_tab, shown = [], [], []
for i, (name, rows) in enumerate(SPRITES):
    is_beam = name.startswith('beam')
    ys = [k for k, r in enumerate(rows) if r.strip('.')]
    xs = [x for r in rows for x, ch in enumerate(r) if ch != '.']
    assert ys, name
    y0, y1, x0, x1 = ys[0], ys[-1], min(xs), max(xs)
    crop = [r[x0:x1 + 1] for r in rows[y0:y1 + 1]]
    rot = rotate(crop)
    ch = y1 - y0 + 1
    asm += [f'spr_{name}:   ; {len(rot[0])}x{len(rot)} turned'] + encode(rot, name)
    inc.append(f'SP_{name.upper():<10} = {i}')
    # the turned box: screen X = box right edge - (cy0 + ch), screen Y = cx0
    dx_tab.append(0 if is_beam else BOX - y0 - ch)
    dy_tab.append(0 if is_beam else x0)
    shown.append(rows)
inc.append('SP_BEAM       = SP_BEAM_0_0')
inc.append(f'SP_COUNT      = {len(SPRITES)}')
names = [n for n, _ in SPRITES]
asm.append('sprite_lo: .byte ' + ', '.join(f'<spr_{n}' for n in names))
asm.append('sprite_hi: .byte ' + ', '.join(f'>spr_{n}' for n in names))
asm.append('sprite_dx: .byte ' + ', '.join(map(str, dx_tab)))
asm.append('sprite_dy: .byte ' + ', '.join(map(str, dy_tab)))
open(os.path.join(OUT, 'art.s'), 'w').write('\n'.join(asm) + '\n')
open(os.path.join(OUT, 'art.inc'), 'w').write('\n'.join(inc) + '\n')
print('src/portrait/font.s art.s art.inc', len(SPRITES), 'sprites')

if len(sys.argv) > 1:
    from PIL import Image
    pal = {'w': (255, 255, 255), 'r': (238, 34, 0), 'b': (68, 102, 255), 'c': (0, 204, 221), 'y': (255, 255, 0), 'g': (0, 204, 68),
           'p': (204, 68, 221), 'o': (255, 136, 0), 'l': (153, 187, 255), 'f': (255, 170, 204), 'x': (170, 170, 190), 'k': (90, 90, 110)}
    S = 8
    sheet = Image.new('RGB', (19 * 10 * S, 10 * S), (0, 0, 0))
    for i, rows in enumerate(shown[:19]):
        for y, r in enumerate(rows):
            for x, ch in enumerate(r):
                if ch != '.':
                    for yy in range(S):
                        for xx in range(S):
                            sheet.putpixel((i * 10 * S + x * S + xx, y * S + yy), pal[ch])
    sheet.save(sys.argv[1])
