#!/usr/bin/env python3
"""Generate src/font.s (3x5 HUD font), src/art.s and src/art.inc (sprites) for the Lynx.

Font: Suzy literal sprites (4 bpp, 4 px wide, 16 bytes per glyph), two copies, pen 1 (white) and pen 2 (red).
Index = ASCII - 32, ' '..'Z'.

Sprites: the alien, bullet and explosion art is decoded from ../c64/src/art.asm. One C64 multicolour pixel
(2 screen pixels wide) becomes one Lynx pixel, and one C64 row becomes one Lynx row (so aliens are 12x11, squarer
than on the C64). Player explosions are tall and get half their rows. Each sprite is cropped to its bounding box;
the crop offset (dx, dy in Lynx pixels) is added when it is drawn, so a sprite goes where the C64 box position / 2 is.
The ship is drawn here (the C64 one is a 1-bit 16 px bitmap). Rows are padded to 14 pixels because the
emulator does not draw the last pixel of a literal line.
Usage: python3 tools/gen_art.py
"""

G = {
    '0': '111101101101111', '1': '010110010010111', '2': '111001111100111', '3': '111001111001111',
    '4': '101101111001001', '5': '111100111001111', '6': '111100111101111', '7': '111001010010010',
    '8': '111101111101111', '9': '111101111001111',
    'A': '111101111101101', 'B': '110101110101110', 'C': '111100100100111', 'D': '110101101101110',
    'E': '111100110100111', 'F': '111100110100100', 'G': '111100101101111', 'H': '101101111101101',
    'I': '111010010010111', 'J': '001001001101111', 'K': '101101110101101', 'L': '100100100100111',
    'M': '101111111101101', 'N': '111101101101101', 'O': '010101101101010', 'P': '111101111100100',
    'Q': '111101101111001', 'R': '110101110101101', 'S': '011100010001110', 'T': '111010010010010',
    'U': '101101101101111', 'V': '101101101101010', 'W': '101101111111101', 'X': '101101010101101',
    'Y': '101101010010010', 'Z': '111001010100111', '-': '000000111000000', '!': '010010010000010',
    ':': '000010000010000', '%': '101001010100101', '.': '000000000000010',
}


def glyph(ch, pen):
    bits = G.get(ch, '0' * 15)
    out = []
    for r in range(5):
        row = bits[r * 3:r * 3 + 3] + '0'                   # 3 pixels + 1 blank column
        n = [pen if b == '1' else 0 for b in row]
        out.append(f'    .byte 3, ${n[0] << 4 | n[1]:02x}, ${n[2] << 4 | n[3]:02x}')
    out.append('    .byte 0')
    return out


lines = ['; Generated by tools/gen_art.py: do not edit.', '        .export font_w, font_r', '', '        .segment "RODATA"']
for name, pen in (('font_w', 1), ('font_r', 2)):
    lines.append(f'{name}:')
    for c in range(32, 91):
        lines.append(f'    ; {chr(c)}')
        lines += glyph(chr(c), pen)
open('src/font.s', 'w').write('\n'.join(lines) + '\n')
print('src/font.s')

# ---------------------------------------------------------------- sprites
import os
import re

C64_ART = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..', 'c64', 'src', 'art.asm')
PENS = {'.': 0, 'w': 1, 'r': 2, 'b': 3, 'c': 4, 'y': 5, 'g': 6, 'p': 7, 'o': 8, 'l': 11, 'f': 15}


def c64_sprites():
    """name -> list of 21 strings of 12 chars: . transparent, y yellow, o own colour, c cyan (multicolour sprites)."""
    parts = re.split(r'^(\w+_sprite):\s*$', open(C64_ART).read(), flags=re.M)
    out = {}
    for i in range(1, len(parts), 2):
        rows = [[int(x, 2) for x in re.findall(r'%([01]{8})', l)]
                for l in re.findall(r'!byte\s+((?:%[01]{8}(?:,\s*)?)+)', parts[i + 1])]
        rows = [r for r in rows if len(r) == 3]
        if parts[i].startswith('player'):
            continue
        out[parts[i][:-7]] = [''.join('.yoc'[(r[0] << 16 | r[1] << 8 | r[2]) >> (22 - 2 * k) & 3] for k in range(12))
                              for r in rows]
    return out


def recolour(rows, own):
    m = {'.': '.', 'y': 'y', 'c': 'c', 'o': own}
    return [''.join(m[ch] for ch in r) for r in rows]


def halve(rows):
    """Merge row pairs (the upper pixel wins), for the tall player explosions."""
    rows = rows + ['.' * len(rows[0])] * (len(rows) % 2)
    return [''.join(a if a != '.' else b for a, b in zip(rows[i], rows[i + 1])) for i in range(0, len(rows), 2)]


SHIP = [
    '.....w.....',
    '.....w.....',
    '....wcw....',
    '....wcw....',
    '...bwwwb...',
    '..rbwwwbr..',
    '.rrbbwbbrr.',
    '.wrbbbbbrw.',
    '.wbbbbbbbw.',
    '.wb.bbb.bw.',
    '.rr..b..rr.',
]
SHIP_CAPTURED = [r.translate(str.maketrans('wbrc', 'fryw')) for r in SHIP]   # the captured fighter: red and pink

c = c64_sprites()
SPRITES = []                                         # (name, rows, dx_extra) in id order
SPRITES.append(('player', SHIP, 1))                  # 11 wide in a 12 wide box: centred
SPRITES.append(('player_red', SHIP_CAPTURED, 1))
SPRITES.append(('pbul', recolour(c['bullet'], 'l'), 0))
SPRITES.append(('ebul', recolour(c['ebullet'], 'r'), 0))
for name, own in (('bee', 'b'), ('bfly', 'r'), ('boss', 'g'), ('bossp', 'p')):
    base = 'boss' if name == 'bossp' else name
    for f in 'ab':
        SPRITES.append((f'{name}_{f}', recolour(c[f'{base}_{f}'], own), 0))
for n in (1, 2, 3):
    SPRITES.append((f'expl{n}', recolour(c[f'expl{n}'], 'o'), 0))
for n in (1, 2, 3, 4):
    SPRITES.append((f'pexp{n}', halve(recolour(c[f'pexp{n}'], 'o')), 0))


# Tractor beam: 4 rows (the C64 draws a row of $66 characters per row, 2..5 cells either side of the boss), each
# 4x4 pixel cell a checkerboard in a shimmering colour; 4 colour phases. id = SP_BEAM + row * 4 + phase.
for r, hw in enumerate((2, 3, 4, 5)):
    for phase in range(4):
        rows = []
        for y in range(4):
            line = ''
            for k in range(2 * hw + 1):
                cc = 'blcl'[(k + r + phase) & 3]
                line += ''.join(cc if (x + y) % 2 == 0 else '.' for x in range(4))
            rows.append(line)
        SPRITES.append((f'beam_{r}_{phase}', rows, 0))


def sprite_data(rows):
    """Crop to the bounding box: (data lines, width, height, dx, dy). Offsets: dx in pixels, dy in rows / 2."""
    ys = [i for i, r in enumerate(rows) if r.strip('.')]
    xs = [x for r in rows for x, ch in enumerate(r) if ch != '.']
    y0, y1, x0, x1 = ys[0], ys[-1], min(xs), max(xs)
    w = x1 - x0 + 1
    lines = []
    for r in rows[y0:y1 + 1]:
        px = [PENS[ch] for ch in r[x0:x1 + 1].ljust(w + 2, '.')]
        px = px[:2 * (w // 2 + 1)]
        lines.append('    .byte %d, ' % (len(px) // 2 + 1) + ', '.join('$%02x' % (px[i] << 4 | px[i + 1]) for i in range(0, len(px), 2)))
    lines.append('    .byte 0')
    return lines, w, y1 - y0 + 1, x0, y0


asm = ['; Generated by tools/gen_art.py: do not edit.', '        .include "art.inc"',
       '        .export sprite_lo, sprite_hi, sprite_dx, sprite_dy', '', '        .segment "RODATA"']
inc = ['; Generated by tools/gen_art.py: do not edit. Sprite ids (index into sprite_lo/hi/dx/dy).']
dx_tab, dy_tab = [], []
for i, (name, rows, extra) in enumerate(SPRITES):
    lines, w, h, dx, dy = sprite_data(rows)
    asm += [f'spr_{name}:   ; {w}x{h}'] + lines
    inc.append(f'SP_{name.upper():<10} = {i}')
    dx_tab.append(dx + extra)
    dy_tab.append(dy // 2)
inc.append('SP_BEAM       = SP_BEAM_0_0')
inc.append(f'SP_COUNT      = {len(SPRITES)}')
names = [n for n, _, _ in SPRITES]
asm.append('sprite_lo: .byte ' + ', '.join(f'<spr_{n}' for n in names))
asm.append('sprite_hi: .byte ' + ', '.join(f'>spr_{n}' for n in names))
asm.append('sprite_dx: .byte ' + ', '.join(map(str, dx_tab)))
asm.append('sprite_dy: .byte ' + ', '.join(map(str, dy_tab)))
open('src/art.s', 'w').write('\n'.join(asm) + '\n')
open('src/art.inc', 'w').write('\n'.join(inc) + '\n')
print('src/art.s src/art.inc', len(SPRITES), 'sprites')

# preview: python3 tools/gen_art.py --preview out.png
import sys
if len(sys.argv) > 2 and sys.argv[1] == '--preview':
    from PIL import Image
    pal = {'w': (255, 255, 255), 'r': (238, 34, 0), 'b': (68, 102, 255), 'c': (0, 204, 221), 'y': (255, 255, 0),
           'g': (0, 204, 68), 'p': (204, 68, 221), 'o': (255, 136, 0), 'l': (153, 187, 255), 'f': (255, 170, 204)}
    S = 8
    sheet = Image.new('RGB', (19 * 16 * S, 22 * S), (0, 0, 0))
    for i, (name, rows, extra) in enumerate(SPRITES[:19]):
        for y, r in enumerate(rows):
            for x, ch in enumerate(r):
                if ch != '.':
                    for yy in range(S):
                        for xx in range(S):
                            sheet.putpixel((i * 16 * S + x * S + xx, y * S + yy), pal[ch])
    sheet.save(sys.argv[2])
